module.exports = {
    preset: "jest-preset-angular",
    roots: ["src"],
    setupFilesAfterEnv: ["<rootDir>/setup-jest.ts"],
    moduleFileExtensions: ["ts", "tsx", "js", "json", "node"],
    moduleNameMapper: {
        "@app/(.*)": "<rootDir>/src/app/$1",
        "@assets/(.*)": "<rootDir>/src/assets/$1",
        "@core/(.*)": "<rootDir>/src/app/core/$1",
        "@env": "<rootDir>/src/environments/environment",
        "@src/(.*)": "<rootDir>/src/src/$1",
        "@services/(.*)": "<rootDir>/src/app/core/services/$1",
        "@helpers/(.*)": "<rootDir>/src/app/helpers/$1",
        "@shared/(.*)": "<rootDir>/src/app/shared/$1",
        "@components/(.*)": "<rootDir>/src/app/components/$1",
        "@gameService": "<rootDir>/src/app/services/game.service.ts",
        "@loadingService": "<rootDir>/src/app/services/loading.service.ts",
        "@gameInterface": "<rootDir>/src/app/interfaces/game.interface.ts",
    },
    coverageDirectory: "./coverage",
    collectCoverageFrom: [
        "src/app/**/*.ts",
        "!src/app/**/*.module.ts",
        "!src/app/mocks/**/*.ts",
        "!src/app/app.routes.ts",
        "!src/app/app.config.ts",
        "!<rootDir>/node_modules/",
        "!<rootDir>/test/",
    ],
};
